# Generated by Django 3.2.13 on 2022-04-20 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Key_Performance_indicator_dingyi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assessment_latitude', models.CharField(max_length=255, verbose_name='考核维度')),
                ('index_name', models.CharField(max_length=255, verbose_name='指标名称')),
                ('key_test', models.CharField(max_length=2000, verbose_name='考核要素')),
                ('basic_score', models.IntegerField(verbose_name='基础分值')),
                ('submit_the_cycle', models.CharField(max_length=255, verbose_name='报送周期')),
                ('evaluation_department', models.CharField(max_length=255, verbose_name='评价部门')),
                ('define_design_formulas', models.CharField(max_length=2000, verbose_name='定义和计算公式')),
                ('evaluation_criterion', models.CharField(max_length=2000, verbose_name='定义和评价标准')),
            ],
            options={
                'verbose_name': '关键业绩指标定义表',
                'verbose_name_plural': '关键业绩指标定义表',
                'db_table': 'key_performance_indicator_dingyi',
            },
        ),
        migrations.CreateModel(
            name='Party_Building_dingyi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_department', models.CharField(max_length=255, verbose_name='考核部门')),
                ('inspection_items', models.CharField(max_length=2000, verbose_name='考核事项')),
            ],
            options={
                'verbose_name': '党建综合考评定义表',
                'verbose_name_plural': '党建综合考评定义表',
                'db_table': 'party_building_dingyi',
            },
        ),
        migrations.CreateModel(
            name='Professional_Evaluation_index_dingyi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_department', models.CharField(max_length=255, verbose_name='考核部门')),
                ('pofessional_name', models.CharField(max_length=255, verbose_name='专业名称')),
                ('points_based_on', models.CharField(max_length=2000, verbose_name='减分依据')),
            ],
            options={
                'verbose_name': '专业评价指标定义表',
                'verbose_name_plural': '专业评价指标定义表',
                'db_table': 'professional_evaluation_index_dingyi',
            },
        ),
        migrations.CreateModel(
            name='Red_Indicator_dingyi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_department', models.CharField(max_length=255, verbose_name='考核部门')),
                ('index_name', models.CharField(max_length=255, verbose_name='指标名称')),
                ('grading', models.CharField(max_length=2000, verbose_name='评分依据')),
            ],
            options={
                'verbose_name': '红线指标定义表',
                'verbose_name_plural': '红线指标定义表',
                'db_table': 'red_indicator_dingyi',
            },
        ),
        migrations.CreateModel(
            name='Safety_Management_dingyi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_department', models.CharField(max_length=255, verbose_name='考核部门')),
                ('points_based_on', models.CharField(max_length=2000, verbose_name='减分依据')),
            ],
            options={
                'verbose_name': '安全管理工作定义表',
                'verbose_name_plural': '安全管理工作定义表',
                'db_table': 'safety_management_dingyi',
            },
        ),
        migrations.CreateModel(
            name='Tupu_Key_Performance_Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_department', models.CharField(max_length=255, verbose_name='责任部门')),
                ('index_name', models.CharField(max_length=255, verbose_name='指标名称')),
                ('inspection_items', models.CharField(max_length=255, verbose_name='考核事项')),
                ('performance_appraisal_cycle', models.CharField(max_length=255, verbose_name='考核周期')),
                ('index_weight', models.IntegerField(verbose_name='指标权重')),
                ('list_type', models.CharField(max_length=255, verbose_name='指标类型')),
                ('complete_value', models.CharField(max_length=255, verbose_name='目标完成值')),
                ('annual_objectives', models.CharField(max_length=255, verbose_name='年度目标')),
                ('supporting_departments_units', models.TextField(verbose_name='支撑部门及单位')),
                ('common_goals', models.TextField(verbose_name='共性目标')),
                ('personality_goal', models.TextField(verbose_name='个性目标')),
                ('concrete_measure', models.TextField(verbose_name='具体措施')),
                ('concrete_measure_sum', models.IntegerField(verbose_name='具体措施数量')),
            ],
            options={
                'verbose_name': '图谱关键业绩指标表',
                'verbose_name_plural': '图谱关键业绩指标表',
                'db_table': 'tupu_key_performance_indicator',
            },
        ),
        migrations.CreateModel(
            name='Tupu_Party_Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_department', models.CharField(max_length=255, verbose_name='责任部门')),
                ('inspection_items', models.CharField(max_length=255, verbose_name='考核事项')),
                ('list_type', models.CharField(max_length=255, verbose_name='清单类型')),
                ('annual_objectives', models.CharField(max_length=255, verbose_name='年度目标')),
                ('supporting_departments_units', models.TextField(verbose_name='支撑部门及单位')),
                ('common_goal', models.TextField(verbose_name='共性目标')),
                ('personality_goal', models.TextField(verbose_name='个性目标')),
                ('concrete_measure', models.TextField(verbose_name='具体措施')),
                ('concrete_measure_sum', models.IntegerField(verbose_name='具体措施数量')),
            ],
            options={
                'verbose_name': '图谱党建综合考评表',
                'verbose_name_plural': '图谱党建综合考评表',
                'db_table': 'tupu_pary_building',
            },
        ),
        migrations.CreateModel(
            name='Tupu_Professional_Evaluation_Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_department', models.CharField(max_length=255, verbose_name='责任部门')),
                ('pofessional_name', models.CharField(max_length=255, verbose_name='专业名称')),
                ('list_type', models.CharField(max_length=255, verbose_name='指标类型')),
                ('annual_objectives', models.CharField(max_length=255, verbose_name='年度目标')),
                ('supporting_departments_units', models.TextField(verbose_name='支撑部门及单位')),
                ('common_goals', models.TextField(verbose_name='共性目标')),
                ('personality_goal', models.TextField(verbose_name='个性目标')),
                ('concrete_measure', models.TextField(verbose_name='具体措施')),
                ('concrete_measure_sum', models.IntegerField(verbose_name='具体措施数量')),
            ],
            options={
                'verbose_name': '图谱专业评价指标表',
                'verbose_name_plural': '图谱专业评价指标表',
                'db_table': 'tupu_professional_evaluation_index',
            },
        ),
        migrations.CreateModel(
            name='Tupu_Red_Indicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_department', models.CharField(max_length=255, verbose_name='责任部门')),
                ('index_name', models.CharField(max_length=255, verbose_name='指标名称')),
                ('supporting_departments_units', models.TextField(verbose_name='支撑部门及单位')),
                ('common_goals', models.TextField(verbose_name='共性目标')),
                ('personality_goal', models.TextField(verbose_name='个性目标')),
                ('concrete_measure', models.TextField(verbose_name='具体措施')),
                ('concrete_measure_sum', models.IntegerField(verbose_name='具体措施数量')),
            ],
            options={
                'verbose_name': '图谱红线指标表',
                'verbose_name_plural': '图谱红线指标表',
                'db_table': 'tupu_red_indicator',
            },
        ),
        migrations.CreateModel(
            name='Tupu_Safety_Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsible_department', models.CharField(max_length=255, verbose_name='责任部门')),
                ('list_type', models.CharField(max_length=255, verbose_name='清单类型')),
                ('annual_objectives', models.CharField(max_length=255, verbose_name='年度目标')),
                ('supporting_departments_units', models.TextField(verbose_name='支撑部门及单位')),
                ('common_goal', models.TextField(verbose_name='共性目标')),
                ('personality_goal', models.TextField(verbose_name='个性目标')),
                ('concrete_measure', models.TextField(verbose_name='具体措施')),
                ('concrete_measure_sum', models.IntegerField(verbose_name='具体措施数量')),
            ],
            options={
                'verbose_name': '图谱安全管理工作表',
                'verbose_name_plural': '图谱安全管理工作表',
                'db_table': 'tupu_safety_management',
            },
        ),
        migrations.CreateModel(
            name='User_login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
                ('is_admin', models.CharField(default=0, max_length=1, verbose_name='是否为管理员，1：是，0：不是')),
            ],
            options={
                'verbose_name': '用户登录表',
                'verbose_name_plural': '用户登录表',
                'db_table': 'user_login',
            },
        ),
    ]
