# Generated by Django 3.2.8 on 2022-04-22 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Key_Performance_indicator_dingyi',
        ),
        migrations.DeleteModel(
            name='Party_Building_dingyi',
        ),
        migrations.DeleteModel(
            name='Professional_Evaluation_index_dingyi',
        ),
        migrations.DeleteModel(
            name='Red_Indicator_dingyi',
        ),
        migrations.DeleteModel(
            name='Safety_Management_dingyi',
        ),
        migrations.DeleteModel(
            name='Tupu_Key_Performance_Indicator',
        ),
        migrations.DeleteModel(
            name='Tupu_Party_Building',
        ),
        migrations.DeleteModel(
            name='Tupu_Professional_Evaluation_Index',
        ),
        migrations.DeleteModel(
            name='Tupu_Red_Indicator',
        ),
        migrations.DeleteModel(
            name='Tupu_Safety_Management',
        ),
        migrations.DeleteModel(
            name='User_login',
        ),
    ]
